---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
    spec:
      containers:
        - name: spc
          image: itsw075/django1:030724
          resources:
            limits:
              cpu: 500m
              memory: 350Mi
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/data"
              name: django-storage
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: django_db
            - name: MYSQL_USER
              value: django_user
            - name: MYSQL_PASSWORD
              value: django_password
      volumes:
        - name: django-storage
          persistentVolumeClaim:
            claimName: django-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
