---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
    spec:
      containers:
        - name: spc
          image: itsw075/django1:030724
          resources:
            limits:
              cpu: 500m
              memory: 350Mi
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP