apiVersion: v1
kind: Pod
metadata:
  name: activity1
  labels:
    app: django
    env: dev
    purpose: understanding
spec:
  containers:
    - name: django
      image: itsw075/260624:django
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "64Mi"
